# This file was *autogenerated* from the file simulation_sage.sage
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_1786 = Integer(1786); _sage_const_0p015 = RealNumber('0.015'); _sage_const_5 = Integer(5); _sage_const_500 = Integer(500); _sage_const_p2 = RealNumber('.2'); _sage_const_p8 = RealNumber('.8'); _sage_const_3000 = Integer(3000)
import numpy as np
import csv
from scipy.stats import bernoulli

G = np.loadtxt(open('/home/elisa/Documents/Projetos/TCC/data/charlie/graph_complete.csv'), delimiter=",")
nodes = np.loadtxt(open('/home/elisa/Documents/Projetos/TCC/data/charlie/original_graph_nodes.csv'), delimiter=",")

# load list of domains in data
with open('/home/elisa/Documents/Projetos/TCC/data/charlie/original_graph_domains_each_node.txt') as f:
    domains = f.read().splitlines()

# create dictionary, one colour to each domain
total_d = list(set(domains))
cols = colors.keys()
color_dict = {'a': _sage_const_1 }

for pos, i in enumerate(total_d):
    color_dict[i] = cols[pos]


#initial conditions
eig = np.linalg.eig(G)[_sage_const_0 ].max()

i0 = np.zeros(G.shape[_sage_const_0 ])
i0[_sage_const_0 ] = _sage_const_1 
s0 = _sage_const_1 -i0


def fun(t, y, pars):
    y = np.array(y)
    i,s = y[:_sage_const_1786 ],y[_sage_const_1786 :]
    A, lamb = pars

    M =  (i * A).sum(axis=_sage_const_1 )
    N = lamb * s
    Q = N*M

    dI = -i + Q
    dS = -Q

    return np.hstack((dI,dS))




def plot_sol(sol, color_dict, domains):
    plots = list_plot([(j[_sage_const_0 ],j[_sage_const_1 ][_sage_const_0 ]) for j in sol[:_sage_const_1786 ]], color=color_dict[domains[_sage_const_0 ]], plotjoined=True, alpha=_sage_const_p8 , gridlines=true)
    for i in range(_sage_const_500 ):
        co = color_dict[domains[i]]
        plots += list_plot([(j[_sage_const_0 ], j[_sage_const_1 ][i]) for j in sol[:_sage_const_1786 ]], color=co, plotjoined=True, alpha=_sage_const_p2 , gridlines=true)
    plots.save('/home/elisa/Documents/Projetos/TCC/data/charlie/simulation.png')



## dI- matrix com a probabilidade do artigo ser infectado no tempo t. dI[0] - artigos infectados no tempo 0
## Infects - matrix boolean com os infectados no tempo t.
## recebe T.solution

def create_dI(sol):
    s = len(T.solution[_sage_const_0 ][_sage_const_1 ])/_sage_const_2 
    dI = np.zeros((len(T.solution), s))
    c = _sage_const_0 
    for i,v in sol:
        dI[c:] =v[:s]
        c+=_sage_const_1 
    return dI


def create_infects(dI):
    B = lambda p: bernoulli.rvs(p, size=_sage_const_1 )[_sage_const_0 ]
    Infects = np.vectorize(B)(dI)

    for pos in range(Infects.shape[_sage_const_1 ]):
        vector = Infects[:,pos]
        indexes = np.where(vector == _sage_const_1 )[_sage_const_0 ]
        if indexes != []:
            i_0,i_n = min(indexes), max(indexes)
            if i_n-i_0+_sage_const_1  != len(indexes):
                Infects[:,pos][i_0:i_n] = _sage_const_1 

    return Infects


def create_infected_matrix(la, Ti):
    T.ode_solve(t_span=[_sage_const_0 , _sage_const_5 ], y_0=list(i0)+list(s0), num_points=_sage_const_3000 , params=[G, la])
    plot_sol(T.solution, color_dict, domains)

    dI = create_dI(T.solution)
    Infects = create_infects(dI)

    return dI, Infects


T = ode_solver()
T.algorithm = "rkf45"
T.function = fun
l = _sage_const_1 /eig + _sage_const_0p015 


dI, Infects = create_infected_matrix(l, T)
np.savetxt('/home/elisa/Documents/Projetos/TCC/data/charlie/dI.csv', dI, delimiter=',')
np.savetxt('/home/elisa/Documents/Projetos/TCC/data/charlie/Infects.csv', Infects, delimiter=',')


#for i in [0.017, 0.02]:
#    dI, Infects = create_infected_matrix(1/eig+i, T)
#    np.savetxt('/home/elisa/Documents/Projetos/TCC/data/charlie/dI_%s.csv' % i, dI, delimiter=',')
#    np.savetxt('/home/elisa/Documents/Projetos/TCC/data/charlie/Infects_%s.csv' % i, Infects, delimiter=',')
